version: '3'
services:
    dice-game:
        container_name: dice-game
        build:
            context: .
            args:
                mock: "false"
            dockerfile: ./Dockerfile
        ports:
            - 8081:80
        networks:
            - dice-game-network
    dice-game-mock:
        container_name: dice-game-mock
        build:
            context: .
            args:
                mock: "true"
            dockerfile: ./Dockerfile
        ports:
            - 8082:80
        networks:
            - dice-game-network
networks:
    dice-game-network: